# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s25:
      dhcp4: false
      dhcp6: false
      addresses:
        - 192.168.100.1/16
      routes:
        -  to: default
           via: 192.168.100.2
      nameservers:
        addresses: [192.168.100.1]
  version: 2
