services:
  pihole:
    image: pihole/pihole
    environment:
      TZ: "Asia/Tehran"
      WEBPASSWORD: "4696048pouria"
      WEB_PORT: "80"
      DNSMASQ_LISTENING: "all"
      LOCAL_IPV4: ${IP}
    restart: "unless-stopped"
    runtime: "crun"
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    volumes:
      - type: volume
        source: pihole
        target: /etc/pihole
      - type: volume
        source: dnsmasq
        target: /etc/dnsmasq.d
    networks:
      - ingress
    cap_add:
      - "NET_ADMIN"
      - "NET_BIND_SERVICE"
      - "NET_RAW"

volumes:
  pihole:
    name: pihole
  dnsmasq:
    name: dnsmasq

networks:
  ingress:
    name: ingress
    driver: overlay
    attachable: true
    external: true
