services:
  pihole:
    image: pihole/pihole
    network_mode: "host"
    environment:
      TZ: "Asia/Tehran"
      WEBPASSWORD: "4696048pouria"
      WEB_PORT: "444"
    restart: "unless-stopped"
    volumes:
      - type: volume
        source: pihole
        target: /etc/pihole
      - type: volume
        source: dnsmasq
        target: /etc/dnsmasq.d
    cap_add:
      - "NET_ADMIN"
      - "NET_BIND_SERVICE"
      - "NET_RAW"

volumes:
  pihole:
  dnsmasq:
